name       : haskell-polyparse
version    : 1.12
release    : 2
source     :
    - http://hackage.haskell.org/package/polyparse-1.12/polyparse-1.12.tar.gz : f54c63584ace968381de4a06bd7328b6adc3e1a74fd336e18449e0dd7650be15
license    : LGPL-2.0
component  : programming.haskell
summary    : A variety of alternative parser combinator libraries, including the original
    HuttonMeijer set.
description: |
    A variety of alternative parser combinator libraries, including the original HuttonMeijer set. The Poly sets have features like good error reporting, arbitrary token type, running state, lazy parsing, and so on. Finally, Text.Parse is a proposed replacement for the standard Read class, for better deserialisation of Haskell values from Strings.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
