name       : haskell-polyparse
version    : '1.13'
release    : 4
source     :
    - https://hackage.haskell.org/package/polyparse-1.13/polyparse-1.13.tar.gz : 1c4c72980e1e5a4f07fea65ca08b2399581d2a6aa21eb1078f7ad286c279707b
license    : LGPL-2.1-or-later
component  : programming.haskell
summary    : A variety of alternative parser combinator libraries, including the original HuttonMeijer set.
description: |
    A variety of alternative parser combinator libraries, including the original HuttonMeijer set. The Poly sets have features like good error reporting, arbitrary token type, running state, lazy parsing, and so on. Finally, Text.Parse is a proposed replacement for the standard Read class, for better deserialisation of Haskell values from Strings.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
